-- Insert captain data

INSERT INTO captains (name, email, phone, bio, avatar_url, years_experience, languages, specialties, certifications, rating, total_reviews, location, country, vessel_name, vessel_type, vessel_capacity, vessel_year) VALUES

-- UK Captains
('Captain James Morrison', 'james.morrison@seafable.com', '+44 7700 900123', 'Born and raised on the Isle of Wight, James has been sailing the Solent waters for over 20 years. Former Royal Navy officer with extensive experience in yacht racing and maritime safety. Passionate about sharing the rich maritime heritage of the English coast.', '/placeholder.svg?height=150&width=150', 22, ARRAY['English', 'French'], ARRAY['Maritime History', 'Yacht Racing', 'Safety Training', 'Coastal Navigation'], ARRAY['RYA Yachtmaster Ocean', 'MCA Commercial Endorsement', 'First Aid at Sea'], 4.9, 156, 'Cowes, Isle of Wight', 'United Kingdom', 'Britannia Spirit', 'Classic Sailing Yacht', 8, 2015),

('Captain Sarah Williams', 'sarah.williams@seafable.com', '+44 7700 900124', 'Marine biologist turned sailing instructor, Sarah combines her love for the ocean with her scientific background. Specializes in wildlife watching tours around the Scottish Highlands and has published research on marine conservation in the North Sea.', '/placeholder.svg?height=150&width=150', 15, ARRAY['English', 'Gaelic'], ARRAY['Marine Biology', 'Wildlife Photography', 'Environmental Education', 'Highland Culture'], ARRAY['RYA Yachtmaster Offshore', 'Marine Biology PhD', 'Wildlife Guide Certification'], 4.8, 203, 'Oban, Scotland', 'United Kingdom', 'Celtic Explorer', 'Motor Yacht', 12, 2018),

('Captain Robert Thompson', 'robert.thompson@seafable.com', '+44 7700 900125', 'Third-generation fisherman from Cornwall who transitioned to luxury sailing experiences. Roberts intimate knowledge of Cornish waters and hidden coves, combined with his storytelling abilities, creates unforgettable journeys along the dramatic Cornish coastline.', '/placeholder.svg?height=150&width=150', 18, ARRAY['English', 'Cornish'], ARRAY['Local History', 'Traditional Fishing', 'Coastal Cuisine', 'Hidden Coves'], ARRAY['RYA Yachtmaster Coastal', 'Commercial Fishing License', 'Food Safety Certificate'], 4.7, 189, 'St. Ives, Cornwall', 'United Kingdom', 'Cornish Pearl', 'Traditional Lugger', 6, 2012),

('Captain Emma Davies', 'emma.davies@seafable.com', '+44 7700 900126', 'Former Olympic sailor who now shares her passion for high-performance sailing with guests. Emma specializes in adrenaline-filled adventures around the Welsh coast, teaching advanced sailing techniques while exploring the stunning Pembrokeshire coastline.', '/placeholder.svg?height=150&width=150', 12, ARRAY['English', 'Welsh'], ARRAY['Performance Sailing', 'Racing Techniques', 'Adventure Sports', 'Coastal Geology'], ARRAY['RYA Yachtmaster Ocean', 'Olympic Sailing Certification', 'Adventure Sports Instructor'], 4.9, 134, 'Tenby, Wales', 'United Kingdom', 'Dragon Fire', 'Racing Yacht', 6, 2020),

-- Mediterranean Captains
('Capitaine Marie Dubois', 'marie.dubois@seafable.com', '+33 6 12 34 56 78', 'Born in Cannes, Marie grew up in a family of restaurateurs and sailors. She combines her culinary heritage with her sailing expertise to offer unique gastronomic experiences along the French Riviera. Certified sommelier and expert in Provençal cuisine.', '/placeholder.svg?height=150&width=150', 16, ARRAY['French', 'English', 'Italian'], ARRAY['Gourmet Cuisine', 'Wine Tasting', 'Provençal Culture', 'Secret Coves'], ARRAY['Permis Côtier', 'Sommelier Certification', 'Food Safety Certificate'], 4.9, 267, 'Cannes, French Riviera', 'France', 'Côte d''Azur', 'Classic Sailing Yacht', 8, 2016),

('Capitano Marco Rossi', 'marco.rossi@seafable.com', '+39 338 123 4567', 'Fourth-generation sailor from the Amalfi Coast, Marco has an encyclopedic knowledge of Italian maritime traditions. His family has been running sailing tours for over 80 years, and he continues the tradition with modern luxury and ancient wisdom.', '/placeholder.svg?height=150&width=150', 25, ARRAY['Italian', 'English', 'Spanish'], ARRAY['Italian Maritime History', 'Traditional Sailing', 'Coastal Cuisine', 'Family Traditions'], ARRAY['Patente Nautica', 'Commercial License', 'Cultural Heritage Guide'], 4.8, 312, 'Amalfi, Italy', 'Italy', 'Bella Vita', 'Traditional Gozzo', 10, 2014),

('Captain Nikos Papadopoulos', 'nikos.papadopoulos@seafable.com', '+30 694 123 4567', 'Santorini native with deep roots in the Cycladic islands. Nikos is a certified dive instructor and underwater photographer who combines sailing with exceptional snorkeling and diving experiences around the volcanic islands of the Aegean Sea.', '/placeholder.svg?height=150&width=150', 19, ARRAY['Greek', 'English', 'German'], ARRAY['Diving Instruction', 'Underwater Photography', 'Volcanic Geology', 'Greek Mythology'], ARRAY['Hellenic Sailing License', 'PADI Dive Master', 'Underwater Photography Certification'], 4.9, 198, 'Santorini, Greece', 'Greece', 'Aegean Dream', 'Catamaran', 12, 2017),

-- Northern European Captains
('Kaptein Lars Andersen', 'lars.andersen@seafable.com', '+47 987 65 432', 'Arctic sailing specialist from the Lofoten Islands. Lars has spent his entire life navigating the dramatic Norwegian fjords and is an expert in midnight sun sailing and northern lights expeditions. Former search and rescue coordinator with unmatched knowledge of Arctic conditions.', '/placeholder.svg?height=150&width=150', 28, ARRAY['Norwegian', 'English', 'German'], ARRAY['Arctic Navigation', 'Northern Lights', 'Fjord Exploration', 'Wildlife Watching'], ARRAY['Norwegian Maritime License', 'Arctic Navigation Certificate', 'Search and Rescue Certification'], 4.8, 145, 'Lofoten Islands, Norway', 'Norway', 'Aurora Borealis', 'Arctic Explorer', 8, 2013),

('Kapitän Hans Mueller', 'hans.mueller@seafable.com', '+49 171 234 5678', 'Master mariner from the Baltic Sea region with expertise in traditional tall ship sailing. Hans operates historic vessel experiences and teaches traditional seamanship while exploring the beautiful German and Danish coastlines.', '/placeholder.svg?height=150&width=150', 21, ARRAY['German', 'English', 'Danish'], ARRAY['Traditional Seamanship', 'Tall Ship Operations', 'Maritime History', 'Baltic Culture'], ARRAY['German Maritime License', 'Tall Ship Master Certificate', 'Maritime History Degree'], 4.7, 176, 'Kiel, Germany', 'Germany', 'Hanse Explorer', 'Traditional Tall Ship', 16, 2010),

('Captain Pieter van der Berg', 'pieter.vandenberg@seafable.com', '+31 6 1234 5678', 'Dutch sailing instructor and yacht designer who specializes in innovative sailing experiences around the Wadden Sea. Pieter combines modern sailing technology with traditional Dutch maritime culture, offering unique insights into sustainable sailing practices.', '/placeholder.svg?height=150&width=150', 14, ARRAY['Dutch', 'English', 'German'], ARRAY['Yacht Design', 'Sustainable Sailing', 'Wadden Sea Ecology', 'Innovation'], ARRAY['Dutch Sailing License', 'Yacht Design Certification', 'Environmental Guide License'], 4.8, 167, 'Amsterdam, Netherlands', 'Netherlands', 'Dutch Innovation', 'Modern Catamaran', 10, 2019);
