-- Insert demo data with proper SeaFable branding

-- Demo user profiles
INSERT INTO user_profiles (id, first_name, last_name, email, phone, date_of_birth, nationality, emergency_contact_name, emergency_contact_phone, sailing_experience, dietary_requirements, special_requirements, marketing_consent, created_at, updated_at) VALUES
('demo-user-001', 'Sarah', 'Johnson', 'demo@SeaFable.com', '+1-555-0123', '1985-06-15', 'United States', 'John Johnson', '+1-555-0124', 'intermediate', ARRAY['vegetarian'], ARRAY[], true, NOW(), NOW()),
('demo-user-002', 'Marco', 'Rodriguez', 'marco@SeaFable.com', '+34-600-123456', '1978-03-22', 'Spain', 'Elena Rodriguez', '+34-600-123457', 'advanced', ARRAY[], ARRAY['wheelchair accessible'], true, NOW(), NOW()),
('demo-user-003', 'Emma', 'Thompson', 'emma@SeaFable.com', '+44-7700-900001', '1992-11-08', 'United Kingdom', 'David Thompson', '+44-7700-900002', 'beginner', ARRAY['gluten-free'], ARRAY[], false, NOW(), NOW());

-- Demo businesses
INSERT INTO businesses (id, business_name, business_type, description, website, phone, email, address_line1, address_line2, city, state_province, postal_code, country, tax_id, business_license, insurance_policy, primary_contact_name, primary_contact_email, primary_contact_phone, business_hours, amenities, certifications, languages_spoken, payment_methods, cancellation_policy, weather_policy, safety_equipment, vessel_specifications, created_at, updated_at) VALUES
('demo-business-001', 'Mediterranean Sailing Adventures', 'sailing_charter', 'Premium sailing experiences along the French Riviera with SeaFable certified captains', 'https://med-sailing.SeaFable.com', '+33-4-93-123456', 'captain@SeaFable.com', 'Port de Cannes', 'Quai Saint-Pierre', 'Cannes', 'Provence-Alpes-Côte d''Azur', '06400', 'France', 'FR12345678901', 'FR-SAILING-2024-001', 'INS-MARINE-789456', 'Captain Marie Dubois', 'marie.dubois@SeaFable.com', '+33-6-12345678', '{"monday": "08:00-18:00", "tuesday": "08:00-18:00", "wednesday": "08:00-18:00", "thursday": "08:00-18:00", "friday": "08:00-18:00", "saturday": "08:00-20:00", "sunday": "08:00-20:00"}', ARRAY['WiFi', 'Refreshments', 'Snorkeling Gear', 'Fishing Equipment'], ARRAY['RYA Yachtmaster', 'First Aid Certified', 'VHF Radio License'], ARRAY['French', 'English', 'Italian'], ARRAY['Credit Card', 'PayPal', 'Bank Transfer'], 'Free cancellation up to 48 hours before departure', 'Trips may be cancelled due to severe weather conditions', ARRAY['Life Jackets', 'Emergency Flares', 'First Aid Kit', 'VHF Radio', 'GPS'], '{"type": "Sailing Yacht", "length": "45ft", "capacity": 8, "year": 2018, "manufacturer": "Beneteau"}', NOW(), NOW());

-- Demo business users
INSERT INTO business_users (id, business_id, user_id, role, permissions, hire_date, employment_status, created_at, updated_at) VALUES
('demo-biz-user-001', 'demo-business-001', 'demo-user-002', 'owner', ARRAY['all'], '2020-01-15', 'active', NOW(), NOW()),
('demo-biz-user-002', 'demo-business-001', 'demo-user-003', 'manager', ARRAY['bookings', 'customers', 'calendar'], '2022-06-01', 'active', NOW(), NOW());

-- Demo equipment
INSERT INTO equipment (id, business_id, name, category, description, quantity_available, daily_rate, hourly_rate, deposit_required, maintenance_schedule, last_maintenance_date, next_maintenance_date, safety_certifications, specifications, created_at, updated_at) VALUES
('demo-equipment-001', 'demo-business-001', 'Premium Snorkeling Set', 'water_sports', 'High-quality mask, snorkel, and fins for underwater exploration', 12, 25.00, 5.00, 50.00, 'monthly', '2024-11-01', '2024-12-01', ARRAY['CE Certified', 'ISO 9001'], '{"mask_type": "tempered_glass", "fin_size": "adjustable", "snorkel_type": "dry_top"}', NOW(), NOW()),
('demo-equipment-002', 'demo-business-001', 'Fishing Rod & Tackle', 'fishing', 'Complete fishing setup with rod, reel, and tackle box', 8, 35.00, 8.00, 75.00, 'weekly', '2024-11-15', '2024-11-22', ARRAY['Fishing License Compliant'], '{"rod_length": "7ft", "reel_type": "spinning", "line_weight": "20lb"}', NOW(), NOW());

-- Demo experiences
INSERT INTO experiences (id, business_id, title, description, short_description, category, difficulty_level, duration_hours, max_participants, min_participants, price_per_person, includes, excludes, meeting_point, what_to_bring, age_restrictions, physical_requirements, weather_dependencies, cancellation_policy, languages, tags, seasonal_availability, special_offers, created_at, updated_at) VALUES
('demo-exp-001', 'demo-business-001', 'Sunset Sailing & Wine Tasting', 'Experience the magic of the French Riviera aboard our luxury sailing yacht. Watch the sun set over the Mediterranean while enjoying premium local wines and gourmet appetizers. Our expert captain will share stories of the coastline and guide you to hidden coves only accessible by boat.', 'Luxury sunset sailing with wine tasting along the French Riviera', 'luxury', 'beginner', 4, 8, 2, 185.00, ARRAY['Professional captain and crew', 'Premium wine selection', 'Gourmet appetizers', 'Snorkeling equipment', 'All safety equipment'], ARRAY['Transportation to marina', 'Gratuities', 'Additional beverages'], 'Port de Cannes, Quai Saint-Pierre', ARRAY['Sunscreen', 'Hat', 'Comfortable clothing', 'Camera'], '{"min_age": 18, "max_age": null}', 'Moderate mobility required for boarding', 'Weather dependent - may be rescheduled', 'Free cancellation 48 hours prior', ARRAY['French', 'English'], ARRAY['sunset', 'wine', 'luxury', 'romantic', 'photography'], '{"available_months": [4,5,6,7,8,9,10], "peak_season": [6,7,8]}', ARRAY[], NOW(), NOW()),
('demo-exp-002', 'demo-business-001', 'Half-Day Coastal Discovery', 'Explore the stunning coastline between Cannes and Antibes on this half-day sailing adventure. Perfect for families and beginners, this trip includes swimming stops, snorkeling opportunities, and a delicious onboard lunch featuring local Mediterranean cuisine.', 'Family-friendly coastal sailing with swimming and lunch', 'family', 'beginner', 5, 10, 4, 125.00, ARRAY['Professional captain', 'Mediterranean lunch', 'Snorkeling gear', 'Swimming stops', 'Safety briefing'], ARRAY['Drinks (available for purchase)', 'Transportation', 'Towels'], 'Port de Cannes, Quai Saint-Pierre', ARRAY['Swimwear', 'Towel', 'Sunscreen', 'Water bottle'], '{"min_age": 6, "max_age": null}', 'Basic swimming ability recommended', 'Operates in most weather conditions', 'Free cancellation 24 hours prior', ARRAY['French', 'English'], ARRAY['family', 'swimming', 'snorkeling', 'lunch', 'coastal'], '{"available_months": [3,4,5,6,7,8,9,10,11], "peak_season": [6,7,8]}', ARRAY['Early bird: 10% off bookings made 30 days in advance'], NOW(), NOW());

-- Demo bookings
INSERT INTO bookings (id, experience_id, user_id, booking_date, experience_date, experience_time, number_of_participants, participant_details, total_amount, booking_status, payment_status, payment_method, special_requests, dietary_requirements, emergency_contact, weather_insurance, cancellation_reason, booking_reference, created_at, updated_at) VALUES
('demo-booking-001', 'demo-exp-001', 'demo-user-001', '2024-11-20', '2024-12-15', '16:00:00', 2, '[{"name": "Sarah Johnson", "age": 39, "emergency_contact": "John Johnson +1-555-0124"}, {"name": "Michael Chen", "age": 42, "emergency_contact": "Lisa Chen +1-555-0125"}]', 370.00, 'confirmed', 'paid', 'credit_card', 'Celebrating anniversary', ARRAY['vegetarian'], 'John Johnson +1-555-0124', true, null, 'SF-2024-001', NOW(), NOW()),
('demo-booking-002', 'demo-exp-002', 'demo-user-003', '2024-11-18', '2024-12-10', '10:00:00', 4, '[{"name": "Emma Thompson", "age": 32, "emergency_contact": "David Thompson +44-7700-900002"}, {"name": "James Wilson", "age": 35, "emergency_contact": "Sarah Wilson +44-7700-900003"}, {"name": "Lucy Wilson", "age": 8, "emergency_contact": "Sarah Wilson +44-7700-900003"}, {"name": "Tom Wilson", "age": 10, "emergency_contact": "Sarah Wilson +44-7700-900003"}]', 500.00, 'confirmed', 'paid', 'paypal', 'First time sailing for the children', ARRAY['gluten-free'], 'David Thompson +44-7700-900002', false, null, 'SF-2024-002', NOW(), NOW());

-- Demo reviews
INSERT INTO reviews (id, booking_id, experience_id, user_id, rating, title, comment, experience_highlights, would_recommend, photos, response_from_business, helpful_votes, created_at, updated_at) VALUES
('demo-review-001', 'demo-booking-001', 'demo-exp-001', 'demo-user-001', 5, 'Absolutely Magical Evening!', 'This was hands down the best part of our trip to the French Riviera! Captain Marie was incredibly knowledgeable and made us feel so welcome. The wine selection was excellent and the sunset views were breathtaking. We saw dolphins! Highly recommend SeaFable for anyone looking for a premium sailing experience.', ARRAY['Stunning sunset views', 'Excellent wine selection', 'Professional and friendly captain', 'Dolphin sighting', 'Perfect weather'], true, ARRAY[], 'Thank you Sarah! It was our pleasure to share this magical evening with you. We''re so glad you enjoyed the dolphin encounter - they always make the experience extra special! - Captain Marie', 8, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
('demo-review-002', 'demo-booking-002', 'demo-exp-002', 'demo-user-003', 4, 'Great Family Experience', 'Perfect introduction to sailing for our family. The kids loved the swimming stops and the captain was very patient with all their questions. The lunch was delicious and the whole crew made sure everyone felt safe and comfortable. Only minor issue was the wind was quite strong, but that''s nature! Would definitely book with SeaFable again.', ARRAY['Kid-friendly crew', 'Great swimming spots', 'Delicious Mediterranean lunch', 'Safety-focused', 'Educational for children'], true, ARRAY[], 'Thank you for choosing SeaFable for your family adventure! We''re delighted the children enjoyed their first sailing experience. The Mediterranean can be unpredictable, but it sounds like you made the most of it! - The SeaFable Team', 3, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days');
